const domPrefix = "component-login";
export const emailInputId = `${domPrefix}-email-input`;
export const emailErrorId = `${domPrefix}-email-error`;
export const passwordInputId = `${domPrefix}-pwd-input`;
export const passwordErrorId = `${domPrefix}-pwd-error`;
export const submitId = `${domPrefix}-submit`;
export const resetId = `${domPrefix}-reset`;
export const notificationId = `${domPrefix}-notification`;
export const LOGIN_PAGE_TITLE = "Login";
